"""Label style templates for product annotations."""

LABEL_STYLES = {
    "badge": {
        "name": "Badge",
        "description": "Compact colored pill, best for prices or short labels",
        "font_size": 36,
        "font_family": "OpenSans-Bold",
        "text_color": (255, 255, 255),
        "text_color_dark": (30, 30, 30),
        "bg_color": (0, 0, 0, 200),
        "border_radius": 14,
        "padding_x": 20,
        "padding_y": 10,
        "shadow": True,
        "shadow_offset": (2, 2),
        "shadow_color": (0, 0, 0, 80),
        "max_width_ratio": 0.5,
        "default_position": "bottom-right",
    },
    "caption": {
        "name": "Caption",
        "description": "Clean text without background, subtle shadow for readability",
        "font_size": 30,
        "font_family": "OpenSans-Regular",
        "text_color": (255, 255, 255),
        "text_color_dark": (40, 40, 40),
        "bg_color": None,
        "border_radius": 0,
        "padding_x": 0,
        "padding_y": 0,
        "shadow": True,
        "shadow_offset": (1, 1),
        "shadow_color": (0, 0, 0, 100),
        "max_width_ratio": 0.8,
        "default_position": "bottom-center",
    },
    "callout": {
        "name": "Callout",
        "description": "White card with feature highlight — looks like a magazine callout",
        "font_size": 32,
        "font_family": "OpenSans-SemiBold",
        "text_color": (30, 30, 30),
        "text_color_dark": (30, 30, 30),
        "bg_color": (255, 255, 255, 230),
        "border_radius": 8,
        "padding_x": 18,
        "padding_y": 10,
        "shadow": True,
        "shadow_offset": (3, 3),
        "shadow_color": (0, 0, 0, 60),
        "max_width_ratio": 0.55,
        "default_position": "bottom-left",
    },
    "minimal": {
        "name": "Minimal",
        "description": "Small text, top corner, no background — for subtle watermarks",
        "font_size": 22,
        "font_family": "OpenSans-Light",
        "text_color": (200, 200, 200),
        "text_color_dark": (100, 100, 100),
        "bg_color": None,
        "border_radius": 0,
        "padding_x": 0,
        "padding_y": 0,
        "shadow": False,
        "shadow_offset": (0, 0),
        "shadow_color": (0, 0, 0, 0),
        "max_width_ratio": 0.4,
        "default_position": "top-left",
    },
    "price_tag": {
        "name": "Price Tag",
        "description": "Large bold price with a colored background strip",
        "font_size": 48,
        "font_family": "OpenSans-ExtraBold",
        "text_color": (255, 255, 255),
        "text_color_dark": (255, 255, 255),
        "bg_color": (220, 50, 50, 220),
        "border_radius": 6,
        "padding_x": 24,
        "padding_y": 12,
        "shadow": True,
        "shadow_offset": (3, 3),
        "shadow_color": (0, 0, 0, 70),
        "max_width_ratio": 0.45,
        "default_position": "bottom-left",
    },
}

FONT_PATHS = {
    "OpenSans": "fonts/OpenSans[wdth,wght].ttf",
    "PlayfairDisplay": "fonts/PlayfairDisplay[wght].ttf",
}

# Weight mapping for variable fonts
FONT_WEIGHTS = {
    "OpenSans-Light": {"weight": 300},
    "OpenSans-Regular": {"weight": 400},
    "OpenSans-SemiBold": {"weight": 600},
    "OpenSans-Bold": {"weight": 700},
    "OpenSans-ExtraBold": {"weight": 800},
    "PlayfairDisplay-Regular": {"weight": 400, "family": "PlayfairDisplay"},
    "PlayfairDisplay-Bold": {"weight": 700, "family": "PlayfairDisplay"},
}

POSITION_OPTIONS = [
    "auto",
    "bottom-left",
    "bottom-right",
    "bottom-center",
    "top-left",
    "top-right",
    "top-center",
]
